[Settings]
ID = NETLIFY_ID

[build]
  publish = ".docz/dist"
  command = "NODE_ENV=production lint-staged && npm run lint:css && npm run test && npm run ratchet && rm -rf .docz && npm run docz:build && npm run storybook:build && npm run test:coverage"

[[headers]]
  for = "/*"
[headers.values]
  Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

